### ISSUE TITLE
Implement hard limits for namespace

### ISSUE THREAD

**Issue by susheel** [EMBL-EBI-TSI/TESK#32]
- [ ] [Configure Memory and CPU Quotas for a Namespace](https://kubernetes.io/docs/tasks/administer-cluster/quota-memory-cpu-namespace/)
- [ ] [Configure Pod Quota for a Namespace](https://kubernetes.io/docs/tasks/administer-cluster/quota-pod-namespace/)
- [ ] Configure [Memory Requests](https://kubernetes.io/docs/tasks/administer-cluster/memory-default-namespace/) & [CPU Requests](https://kubernetes.io/docs/tasks/administer-cluster/cpu-default-namespace/) and Limits for a Namespace

Also see https://git.k8s.io/community/contributors/design-proposals/resource-management/admission_control_limit_range.md

**Comment by aniewielska** [comment]
This issue does not really say, what we want to achieve by that (possibly resource limits for users/groups of users of TESK - taking #31 in consideration). At the moment TESK uses one namespace and all the objects are created there. There are no scoped namespaces in K8s AFAIK, so no way to implement #31 natively.
In this task we will investigate then, how applying Quotas to namespaces (one in our case) works in practice for our case of running multiple Jobs rather than services.
1) Object count Quota for Jobs:
a) counts everything in `etcd` - meaning Jobs in any status (also Completed). If Quota is exceeded, create Job API returns: 
```
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"jobs.batch \"task-65cacf48\" is forbidden: exceeded quota: object-quota-demo, requested: count/jobs.batch=1, used: count/jobs.batch=4, limited: count/jobs.batch=4","reason":"Forbidden","details":{"name":"task-65cacf48","group":"batch","kind":"jobs"},"code":403}
```
It can happen in our case for taskmaster (no task run) or executor/filer (taskmaster restarts and then fails)
