### ISSUE TITLE
Suggestion: Deployment through helm instead of ad-hoc jinja templating

### ISSUE THREAD

**Issue by pcm32** [EMBL-EBI-TSI/TESK#49]
Hi there!

Nice work here! I would suggest using helm for your application deployment in k8s:
https://github.com/kubernetes/helm

We have been using it in PhenoMeNal for a few projects, simplifies life quite a lot. Let me know if you want to have a chat about it.

**Comment by giannidallatorre** [comment]
Hi Pablo,
I am copying here the answer I gave you on `embl-ebi-developers` Slack channel, just for the records.
Kind regards,
Gianni.

> Hi @Pablo thanks for the suggestion.
I was reading something about Helm when was I looking for a solution in how to template the Kubernetes yaml files, but they were saying that it is overkilling for such a simple scope. The use of `Jinja2` templates is actually enough for maintaining the minimal differences we have and has the advantage of avoiding the dependency to `helm` at the cost of the one to a `Jinja2` cli or the more generic python `Jinja2` library.
Anyway considering your positive feedback I will give a try to `helm`, also because I am facing some limitations in the `shinto-cli` that we are using.
